version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "my-rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "bikov"
      RABBITMQ_DEFAULT_PASS: "blat"
      RABBITMQ_NODENAME: "rabbit@my-rabbit"
    ports:
      - "8080:15672"
    networks:
      vpcbr:
        ipv4_address: 172.16.238.101
    labels:
      NAME: "rabbit"
  redis:
    image: "redis"
    labels:
      NAME: "redis"
  networks:
    vpcbr:
      ipv4_address: 172.16.238.102
  rasp:
    image: "bikov/rasp"
    deploy:
      replicas: 3
    labels:
      NAME: "rasp"
    links:
      - rabbit:mq
      - redis:redis
    depends_on:
      - "rabbit"
    environment:
      MQ_URL: "amqp://bikov:blat@mq"
      REDIS_URL: "redis"
  godfather:
      image: "bikov/godfather"
      labels:
        NAME: "godfather"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      links:
        - rabbit:mq
        - redis:redis
      depends_on:
        - "rasp"
      environment:
        MQ_URL: "amqp://bikov:blat@mq"
        REDIS_URL: "redis"

networks:
  vpcbr:
    driver: bridge
      enable_ipv6: true
      ipam:
        driver: default
        config:
        - subnet: 172.16.238.0/24
        - subnet: 2001:3984:3989::/64