version: '3'
services:
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "my-rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "bikov"
      RABBITMQ_DEFAULT_PASS: "blat"
      RABBITMQ_NODENAME: "rabbit@my-rabbit"
    ports:
      - "8080:15672"
    labels:
      NAME: "rabbit"
  rasp:
    image: "bikov/rasp"
    deploy:
      replicas: 3
    labels:
      NAME: "rasp"
    links:
      - rabbit:mq
    depends_on:
      - "rabbit"
  godfather:
      image: "bikov/godfather"
      labels:
        NAME: "godfather"
      links:
        - rabbit:mq
      depends_on:
        - "rasp"